### ISSUE TITLE
Convolution-Free Medical Image Segmentation using Transformers

### ISSUE THREAD

**Issue by WinsaW** [The-AI-Summer/self-attention-cv#12]
Thank you very much for your contribution. As a novice, I have a doubt. In tranf3dseg, the output of the model is the prediction segmentation of the center patch, so how can I get the segmentation of the whole input image? I am looking forward to any reply.

**Comment by black0017** [comment]
Hello i think we solved this question in a prev. issue:

https://github.com/The-AI-Summer/self-attention-cv/issues/2

Take a look at this tutorial example https://colab.research.google.com/drive/19q84fPhPhGmX36SMdrWfoJBN7k6eoSR2?usp=sharing to see how you can use it for inferencing the whole 3 vol.

Let me know if you manage to have good results with it. Thanks!
