### ISSUE TITLE
so, how to use it? I want to use cityscape datasets test this method

### ISSUE THREAD

**Issue by huajng** [The-AI-Summer/self-attention-cv#13]

**Comment by black0017** [comment]
hi, the package provides only the architectures and modules. some pytorch knowledge to set your project up is required. 

best,
N.

**Comment by huajng** [comment]
Thank you!



---- 回复的原邮件 ----
| 发件人 | Adaloglou ***@***.***> |
| 日期 | 2022年02月09日 23:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [The-AI-Summer/self-attention-cv] so, how to use it? I want to use cityscape datasets test this method (Issue #13) |

hi, the package provides only the architectures and modules. some pytorch knowledge to set your project up is required.

best,
N.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
