### ISSUE TITLE
How do I import a pre-trained VIT model into the TransUnet interface?

### ISSUE THREAD

**Issue by 834799106** [The-AI-Summer/self-attention-cv#4]
Looking forward to your reply

**Comment by black0017** [comment]
I added a parameter to pass your own transformer here:  https://github.com/The-AI-Summer/self-attention-cv/blob/main/self_attention_cv/transunet/trans_unet.py#L9

Please note that you have to use the input vit channels also. to the best of my knowledge, they used a vit type transformer in the paper with patch_size 1 and something like 128*8 channels and not 3 as in a vit trained in rgb images

So l'm not sure if it fits your solution. let me know
