### ISSUE TITLE
Request for Including UNETR

### ISSUE THREAD

**Issue by Siyuan89** [The-AI-Summer/self-attention-cv#6]
Thanks for great work ! I noticed nice implementation of this paper (https://arxiv.org/abs/2103.10504) here:

https://github.com/tamasino52/UNETR/blob/main/unetr.py

It would be great if this can also be included in your repo, since it comes with lots of other great features. So we can explore more. 

Thanks ~

**Comment by black0017** [comment]
Interesting work! I am interested in reimplementing/adjusting the official repo in this one.

From a first pass I noticed that they do not used any pretraining, that sounds very interesting!

Thanks for letting me know about this work! @Siyuan89

**Comment by black0017** [comment]
added on v1.2 @Siyuan89

**Comment by Siyuan89** [comment]
Thank you @black0017 for your work. Also any working example of how to use it ?
