### ISSUE TITLE
use AxialAttention on gpu

### ISSUE THREAD

**Issue by siat-qinjin** [The-AI-Summer/self-attention-cv#7]
I try to use AxialAttention on gpu, but I get a mistake.Can you give me some tips about using AxialAttention on gpu.
Thanks!
mistake:
RuntimeError: expected self and mask to be on the same device, but got mask on cpu and self on cuda:0

**Comment by black0017** [comment]
is it the same as this https://github.com/The-AI-Summer/self-attention-cv/issues/3 ?
if so i have to update the pip version

**Comment by black0017** [comment]
fixed in v1.2 @siat-qinjin
