### ISSUE TITLE
ResNet + Pyramid Vision Transformer Version 2

### ISSUE THREAD

**Issue by khawar512** [The-AI-Summer/self-attention-cv#8]
Thank you for your work with a clear explanation. As you know, ViT doesn't work on small datasets and I am implementing ResNet34 with Pyramid Vision Transformer Version 2 to make it better. The architecture of ViT and PVT V2 is completely different. Could you provide me some help to implement it? please

**Comment by black0017** [comment]
Hello have you checked the authors' repo https://github.com/whai362/PVT ?

Is the model you reference (ResNet34 with Pyramid Vision Transformer Version 2 ) described or implemented in the paper?

I am also looking on the pyramid vision transformer concept.

**Comment by khawar512** [comment]
No, they use the ResNet18 model with PVT but I want to use it. do you have any idea? We can work together and discuss PVT concepts.

**Comment by black0017** [comment]
do you have any intuition why this would help you solve your task? i would like to add some version of pvt but i am currently short on time
