### ISSUE TITLE
Regression with attention

### ISSUE THREAD

**Issue by alemelis** [The-AI-Summer/self-attention-cv#9]
Hello!

thanks for sharing this nice repo :)

I'm trying to use ViT to do regression on images. I'd like to predict 6 floats per image.

My understanding is that I'd need to simply define the network as

```python
vit = ViT(img_dim=128,
               in_channels=3,
               patch_dim=16,
               num_classes=6,
               dim=512)
```

and during training call

```python
vit(x)
```

and compute the loss as MSE instead of CE.

The network actually runs but it doesn't seem to converge. Is there something obvious I am missing?

many thanks!

**Comment by black0017** [comment]
Hello I dont have practical experience with regression tasks. I recently came up on this article for vanilla transformers and regression https://www.linkedin.com/pulse/how-i-turned-nlp-transformer-time-series-predictor-zimbres-phd/

From a quick glance I see that the author uses a super tiny transformer `d_model=4 , d_ff=32` while the original model has`d_model=512, d_ff=2048`

Let me know if it helps.
